name: Pack Templates

on:
  workflow_dispatch:

env:
  pack-root: "${{ github.workspace }}/nupkgs"

jobs:

  pack-templates:
    runs-on: ubuntu-latest

    env:
      template-pack: "source/templatepack.csproj"
      output-name: "finebits.dotnet.templates"

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: New version number
      id: version-number
      uses: finebits/github-actions/version-number@main

    - name: Pack templates
      run: dotnet pack "${{ env.template-pack }}" --nologo --output="${{ env.pack-root }}" --p:PackageVersion="${{ env.version }}"
      env:
        version: ${{ steps.version-number.outputs.semantic-version }}

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: pack
        path: |
          ${{ env.pack-root }}

  validate-templates:
    runs-on: ubuntu-latest
    needs: [ pack-templates ]
    strategy:
      matrix:
        template-name:
          [
            "finebits-console-app",
          ]
          
    env:
      template-name: ${{ matrix.template-name }}
      
    steps:
      - name: Install .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - uses: actions/download-artifact@v3
        with:
          name: pack
          path: ${{ env.pack-root }}

      - name: Install package
        run: dotnet new install "${{ env.pack-root }}/*.nupkg"
       
      - name: Create project
        run: dotnet new ${{ env.template-name }} -o "new_project"

  deploy-templates:
    runs-on: ubuntu-latest
    needs: [ validate-templates ]
    steps:
      - name: Install .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - uses: actions/download-artifact@v3
        with:
          name: pack
          path: ${{ env.pack-root }}
          
      - name: Publish NuGet package
        run: dotnet nuget push "${{ env.pack-root }}/*.nupkg" --api-key "${{ secrets.NUGET_APIKEY }}" --source https://api.nuget.org/v3/index.json --skip-duplicate